# Generated by Django 4.1.4 on 2023-05-19 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realization', '0002_basket_basketitems_userorder_question_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 19, 31, 6, 222489, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 19, 31, 6, 223489, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='order_items',
            field=models.ManyToManyField(blank=True, default=list, to='realization.basketitems'),
        ),
    ]
