# Generated by Django 4.1.4 on 2023-05-23 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realization', '0002_basket_question_comment_basketitems_basket_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 16, 54, 54, 758583, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 16, 54, 54, 758583, tzinfo=datetime.timezone.utc)),
        ),
    ]
