# Generated by Django 4.1.4 on 2023-05-19 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realization', '0003_alter_comment_date_alter_question_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 19, 42, 18, 142523, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 19, 42, 18, 143524, tzinfo=datetime.timezone.utc)),
        ),
    ]
